# This is a basic workflow is meant to watch octopus-freeze.json file
# when a change is pushed we trigger the Webcardinal-workspace to start the build process for each distribution of Webcardinal.

name: BUILD-DISTRIBUTIONS

# Controls when the action will run.
on:
  # Triggers the workflow on push events only for the master branch and if the octopus-freeze.json was changed
  push:
    branches: [ master ]
    paths:
      - 'octopus-freeze.json'

# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Node version
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # run tests
      - name: Run tests
        run: |
        curl -XPOST -u "${{secrets.USERNAME}}:${{secrets.TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/webcardinal/webcardinal-workspace/dispatches --data '{"event_type": "start-build-distributions"}'
